server:
  port: 58888
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medical  # 数据库连接URL
    username: root  # 数据库用户名
    password: 123456  # 数据库密码
    driver-class-name = com.mysql.cj.jdbc.Driver  # 数据库驱动类名
  application:
    name: DBConnection
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: DBConnection
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        metadata:
          mydata: hello

        naming-load-cache-at-start: false
        namespace: dev
        cluster-name: Cluster-B
        group: myGroup
        register-enabled: true

logging:
  level:
    com.broadview.coupon: debug

